### ISSUE TITLE
Module name conflicts with popular lib attrs

### ISSUE THREAD

**Issue by merwok** [denis-ryzhkov/attr#2]
It turns out that the attrs* module defines a package named `attr`, which shadows this projects’s `attr` module.  Given their popularity,  I won’t ask them to rename, but this project could.

I don’t use attrs but the latest pytest depends on it.  In the meantime I have inlined the attr function in my code.

\* https://github.com/python-attrs/attrs

**Comment by denis-ryzhkov** [comment]
Thanks, @merwok !

Please `pip install -U attr` and use the new alias:

    from dry_attr import attr

**Comment by merwok** [comment]
That was fast!  Thanks.
