### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by toddrme2178** [denis-ryzhkov/attr#4]
I am trying to package attr for openSUSE. However, there is no license file I can find, either in the github or tarball. In order for people to know how they can use your code it is really important to have a license file. Would it be possible to add one? Thank you.

**Comment by garry-jeromson** [comment]
Seconding this request, so the package can be included in a Yocto build.

**Comment by fabaff** [comment]
This is also required for the Fedora package.

**Comment by denis-ryzhkov** [comment]
Done. Thank you and sorry for huge delay. For some reason notifications from this old repo never reached my email.
v0.3.2 is published: https://pypi.org/project/attr/

**Comment by fabaff** [comment]
Thanks
